### ISSUE TITLE
疑似bug

### ISSUE THREAD

**Issue by qinjin2** [MrXiaoM/LocalFileService#1]
使用napcat4.2.7时，如果使用该插件，则发送图片的时候会报错，导致图片发送失败，不使用本插件则正常
日志如下：

11-29 17:48:05 [error] 猫 | 发生错误 Error: ENOENT: no such file or directory, copyfile '/var/folders/pm/sktjbvs534x1k_bk8cxfw8hh0000gn/T/tmp17563536740262929673.tmp' -> '/Users/mac/Library/Containers/com.tencent.qq/Data/.config/QQ/NapCat/temp/94444137-3a57-400e-97b2-b5ef6a536c59.tmp'
    at Object.copyFileSync (node:fs:3013:11)
    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:2967)
    at uri2local (file:///Users/mac/Library/Containers/com.tencent.qq/Data/Documents/napcat/napcat.mjs:20904:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///Users/mac/Library/Containers/com.tencent.qq/Data/Documents/napcat/napcat.mjs:48033:9)
    at async image (file:///Users/mac/Library/Containers/com.tencent.qq/Data/Documents/napcat/napcat.mjs:47661:10)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///Users/mac/Library/Containers/com.tencent.qq/Data/Documents/napcat/napcat.mjs:47970:17)
    at async SendGroupMsg._handle (file:///Users/mac/Library/Containers/com.tencent.qq/Data/Documents/napcat/napcat.mjs:48181:52)
    at async SendGroupMsg.websocketHandle (file:///Users/mac/Library/Containers/com.tencent.qq/Data/Documents/napcat/napcat.mjs:43086:23)

**Comment by MrXiaoM** [comment]
提供的信息不全。
比如发送图片的消息json、是否检查过相关的图片文件是否存在等等

**Comment by qinjin2** [comment]
@MrXiaoM 通过url发送图片的，之前是napcat的报错日志，下面是mcl的报错日志：

2024-11-29 17:47:10 W/Onebot: 请求失败: [send_group_msg] 请求失败: app=NapCat.Onebot v4.2.7, message=ENOENT: no such file or directory, copyfile '/var/folders/pm/sktjbvs534x1k_bk8cxfw8hh0000gn/T/tmp7576549489272073045.tmp' -> '/Users/mac/Library/Containers/com.tencent.qq/Data/.config/QQ/NapCat/temp/9a9f7c2c-b6fd-4438-9112-df939fe12523.tmp', retJson={"status":"failed","retcode":1200,"data":null,"message":"ENOENT: no such file or directory, copyfile '/var/folders/pm/sktjbvs534x1k_bk8cxfw8hh0000gn/T/tmp7576549489272073045.tmp' -> '/Users/mac/Library/Containers/com.tencent.qq/Data/.config/QQ/NapCat/temp/9a9f7c2c-b6fd-4438-9112-df939fe12523.tmp'","wording":"ENOENT: no such file or directory, copyfile '/var/folders/pm/sktjbvs534x1k_bk8cxfw8hh0000gn/T/tmp7576549489272073045.tmp' -> '/Users/mac/Library/Containers/com.tencent.qq/Data/.config/QQ/NapCat/temp/9a9f7c2c-b6fd-4438-9112-df939fe12523.tmp'","echo":13}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-11-29 17:47:10 V/Bot.1792896458: Group(740479927) <- [overflow:image,url=file:///var/folders/pm/sktjbvs534x1k_bk8cxfw8hh0000gn/T/tmp7576549489272073045.tmp][overflow:image,url=file:///var/folders/pm/sktjbvs534x1k_bk8cxfw8hh0000gn/T/tmp2788182803878319043.tmp][overflow:image,url=file:///var/folders/pm/sktjbvs534x1k_bk8cxfw8hh0000gn/T/tmp12858145422939349037.tmp]
2024-11-29 17:47:10 E/MAH Access: java.lang.IllegalStateException: 消息发送失败，详见网络日志 (logs/onebot/*.log) 和 Onebot 实现 (NapCat.Onebot v4.2.7) 的日志
java.lang.IllegalStateException: 消息发送失败，详见网络日志 (logs/onebot/*.log) 和 Onebot 实现 (NapCat.Onebot v4.2.7) 的日志
	at top.mrxiaom.overflow.internal.utils.TransformerUtilsKt.safeMessageIds(TransformerUtils.kt:102)
	at top.mrxiaom.overflow.internal.contact.GroupWrapper.sendMessage(GroupWrapper.kt:203)
	at top.mrxiaom.overflow.internal.contact.GroupWrapper$sendMessage$1.invokeSuspend(GroupWrapper.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

已经没有其他日志信息了....出错和不出错唯一的变量就是是否使用此插件

**Comment by MrXiaoM** [comment]
配置文件的 useFileBlacklist 加上 tmp 解决
